---
title: "Histogram Challenge"
output: github_document
---

## The Challenge

Clark and Golder (2006) claim: 

> Social heterogeneity increases the number of parties, but only when electoral institutions are sufficiently permissive.

Evaluate this claim using **using only histograms**.

## The Hypothesis

[Clark and Golder (2006)](http://mattgolder.com/files/research/cps2.pdf) write the following: 

> These strategic considerations indicate that electoral institutions modify the relationship between socioeconomic cleavages and the number of parties. In particular, this framework indicates that there are two reasons why a country might have a small number of parties. First, it could be the case that the demand for parties is low because there are few social cleavages. In this situation, there would be few parties whether the electoral institutions were permissive or not. Second, it could be the case that the electoral system is not permissive. In this situation, there would be a small number of parties even if the demand for political parties were high. Only a polity characterized by both a high degree of social heterogeneity and a highly permissive electoral system is expected to produce a large number of parties. This line of reasoning generates the following hypothesis: **Social heterogeneity increases the number of parties, but only when electoral institutions are sufficiently permissive.**

## The Data

The data below (from the authors) contain measure of the key concepts.

The numeric variable `average_magnitude` and its factor variant `electoral_system` measure permissiveness. Higher values indicate a more permissive electoral system. 
The numeric variable `eneg` and its factor variant `social_heterogeneity` measure social heterogeneity. Higher values indicate a more heterogeneous society.

I included a comma-separated version of the data set as well, and I made a [codebook](https://pos5737.github.io/data/parties-codebook.html).

```{r message=FALSE, warning=FALSE}

# load packages
library(tidyverse)

# load data
cg_df <- read_rds("data/parties.rds") %>%
  glimpse()

# create histogram
ggplot(cg_df, aes(x = enep)) + 
  geom_histogram()
```


## The Histograms

Create histograms (or variants, such as density plots) to evaluate Clark and Golder's argument. Be creative, but **cleary show their key claim**: *Social heterogeneity increases the number of parties, but only when electoral institutions are sufficiently permissive.*

Feel free to use whatever software you like and manipulate the data in any way that's helpful.
